### PR TITLE
2 autons done

### PR DESCRIPTION
**Pull request by BA101-Auroad**
Auton 1 -Goal + Dock 

Auton 2 - Goal 

Auton 3 - TBD 

Auton 4 - TBD

### CODE REVIEW

**Comment by LED-esma** [comment]
Everything seems good to me, except the part for autonomousInIt. We need to add logic for choosing that lines up with the auto selector, for that to happen.

**Comment by BA101-Auroad** [comment]
Just commit and we can add the logic to AutonomousInIt

**Comment by BA101-Auroad** [comment]
-later on

**Comment by LED-esma** [comment]
Quick removal of one of the two autonomous != null real quick before the merge would be much appreciated.

**Comment by BA101-Auroad** [comment]
I'll just do comment instead of removal just in case

**Comment by LED-esma** [comment]
Okay, Thank you

**Review by LED-esma — APPROVED** [review]
Changes do as they state, and setup for future programming.

**Pull request merged**
